### PR TITLE
post processing scripts

### PR DESCRIPTION
**Pull request by FraunhoferItalia**
Hi,

I would like to introduce the possibility to call bash script after robot deploy. 

The first idea that came to my mind is to add a `post_processing_scripts` key to the `config_file.yaml` that is a list of scripts to run after robot deploy. As it can be noticed from the modifications done to `URDF_writer.py` the script will have a common argument interface:
- destination-folder: as your `deploy.sh` script
- package name: name of the generated `modularbot` package

What do you think? Alternatives or improvements are welcome.

Thanks,
Marco

### CODE REVIEW

**Comment by EdoardoRomiti** [comment]
Hi @MarcoMagriDev, @FraunhoferItalia , it seems like a useful feature.
I've just made some modifications so to avoid code duplication, since the expansion of `$(rospack find ....)` commands is already done in other places in the code.
To do this I had to modify slightly the config: transforming the list in a key:value map. In this way we can use the same methods we use for the `resources` . This shouldn't create many issues for you I guess.
Moreover, I modified the regex so that also other commands such as `$(PWD)` could be used (not only `rospack find`).

Does this work for you? Otherwise, feel free to propose other changes before we merge.

**Comment by MarcoMagriDev** [comment]
Just a few comments:
1) This error is now present when you launch `robot-design-studio` preventing the application to start. I have hotfixed it by simply removing the corresponding line from the config file. 
image
Is this the intent behavior when a resource package is not found? what do you think of adding a catch to the exception and print a warning instead?
2) During my first test I forgot to source the package in which the post elaboration script is contained and I got on the terminal:
Screenshot from 2023-12-15 16-39-50 
On the other hand the gui reports "Deplayment successfull". Is it possible to forward this error also to the GUI so that the user (even not by looking at the terminal) is able to see that something has gone wrong?

**Comment by EdoardoRomiti** [comment]
1. The config file goal is to specify what resources are available on the specific machine. So if you don't have the `dagana_ros_pkg` it should be removed from there, otherwise each "resource" you use will be looked for also at  `$(rospack find dagana_urdf)`. If we catch the exception instead of raising it and print a warning message this would be the result:
Screenshot from 2023-12-15 18-13-08
I just changed this behavior by printing a warning instead of re-raising the exception, but I think it still is better to configure the config ;)

2. The Deployment in that case was indeed successful, so it's probably correct the GUI shows that. What failed is the post-processing-script. In order to communicate that to the GUI we would need to raise the exception instead of passing here: 
https://github.com/FraunhoferItalia/modular_hhcm/blob/026dd3f4f26269746f213eea6689a6700d4c66a7/src/modular/URDF_writer.py#L4074C8-L4082C21
I thought it was better to avoid raising an exception because there could be more than one post-processing-script, and maybe it's not always true that if one fails we want to stop the execution of the others. 
If you think it is better just change `pass` to `raise(e)` in line 4082 and the error message will be displayed by the GUI. Feel free to push it on this `post-processing-script` branch.

**Comment by MarcoMagriDev** [comment]
1. It was just to highlight a difference with respect to the previous behavior in which even if a do not have the packages listed in the `config_file.yaml` nothing happens. Anyway i will remove the `dagana_path` from pino config file for clarity
2. Maybe we can think of explicitly defining if a post processing script is mandatory or not by modifying the `post_processing_script` session in a way similar to this one. 
    ```yaml
    post_processing_scripts: 
      fhi_post_generation_script: 
        file: '$(rospack find fhi_xbot_plugins)/scripts/post_generation.sh'
        required: true
    ```
    By doing so the user may be allowed to specify if the failure of one script will cause the failure of the model generation. Nevertheless, we can also leave compatibility to previous syntax:
    ```yaml
    post_processing_scripts: 
      fhi_post_generation_script: '$(rospack find fhi_xbot_plugins)/scripts/post_generation.sh'
    ```
    By assuming `required: false` by default. 
    What do you think @EdoardoRomiti?

**Comment by EdoardoRomiti** [comment]
- Ok so with https://github.com/ADVRHumanoids/modular_hhcm/pull/7/commits/c085ef262077641704660a9e331b4f1ecf0d1d44 a warning is printed instead of raising an exception when a resource dir is not found.
- With https://github.com/ADVRHumanoids/modular_hhcm/pull/7/commits/31809c71276f6e0f1bdd1cbc60e47f9774e68266 I've removed the last hardcoded value regarding the resources meshes. So if in the furture you need to add another resource dir (like fhi_resources) it is now sufficient to add it in the config.
- Finally, with https://github.com/ADVRHumanoids/modular_hhcm/pull/7/commits/2533d9c344acba57a034a8a425b2a6f81169c085 I've adopted your suggestion and a `required` field has been added to the config under the "post_processing_script".

**Pull request merged**
